# FoodBase without perishable stuff
- type: entity
  abstract: true
  parent: EdibleBase
  id: FoodUnperishableBase
  components:
  # FoodBase, no perishable stuff
  - type: SpaceGarbage
  # FoodInjectableBase
  - type: InjectableSolution
    solution: food
  - type: RefillableSolution
    solution: food

# FoodProduceBase without perishable stuff
- type: entity
  abstract: true
  parent: FoodUnperishableBase
  id: FoodProduceUnperishableBase
  components:
  # FoodProduceBase
  - type: SolutionContainerManager
  - type: Sprite
    state: produce
  - type: Produce
  - type: PotencyVisuals
  - type: Appearance
  - type: Extractable
    grindableSolutionName: food
